# Generated by Django 5.2.4 on 2025-07-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetenaArchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(choices=[('final', 'Final'), ('mid', 'Mid'), ('quiz', 'Quiz')], default='TEST', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_email',
            field=models.EmailField(default='test@etdu.et', max_length=254, verbose_name='Organization Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='staffID',
            field=models.CharField(default='ETDU/20067/test', max_length=50, verbose_name='given by organization'),
        ),
        migrations.CreateModel(
            name='DifficultyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_score', models.IntegerField(choices=[('1', 'VERY EASY'), ('2', 'EASY'), ('3', 'MODERATE'), ('$', 'HARD'), ('5', 'VERY HARD')])),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetenaArchive.exam')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
