# Generated by Django 5.2.4 on 2025-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetenaArchive', '0002_alter_user_options_exam_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyrating',
            name='difficulty_score',
            field=models.CharField(choices=[('1', 'VERY EASY'), ('2', 'EASY'), ('3', 'MODERATE'), ('4', 'HARD'), ('5', 'VERY HARD')], max_length=2),
        ),
    ]
