# Generated by Django 5.2.4 on 2025-08-28 08:10

import django.db.models.deletion
import file_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetenaArchive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=file_api.utils.exam_file_path)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetenaArchive.exam')),
            ],
        ),
    ]
