# Generated by Django 5.2.4 on 2025-09-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetenaArchive', '0004_alter_user_staffid_alter_user_studentid'),
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfile',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_file', to='fetenaArchive.exam'),
        ),
    ]
