# Generated by Django 5.2.4 on 2025-07-21 08:50

import file_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfile',
            name='file',
            field=models.FileField(upload_to=file_api.utils.exam_file_path),
        ),
    ]
